version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: es01
    networks:
      - elastic
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 1GB
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kib01
    networks:
      - elastic
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

networks:
  elastic:
    driver: bridge

volumes:
  esdata:
    driver: local
