source:
  type: postgres
  host: aws-0-ap-south-1.pooler.supabase.com
  port: 5432
  user: postgres.dkyzqpmregyfppsimuiq
  password: raushansujal2003
  dbname: postgres
  schema: public
  table: TutorialCategory

destination:
  type: elasticsearch
  host: localhost
  port: 9200
  ssl: true
  ssl_certificate: ./http_ca.crt
  username: elastic
  password: kpsE_NH4-I=uw8jjbT-R
  index: categories

mapping:
  properties:
    id:
      source: id
      type: text
    categoryName:
      source: categoryname
      type: text
    createdAt:
      source: createdat
      type: date
    updatedAt:
      source: updatedat
      type: date

sync:
  type: full
  batch_size: 1000
  max_workers: 4
  conflict_strategy: replace